name: "Build and Deploy to Cloud Run"

on:
  push:
    branches:
      - "master"

env:
  PROJECT_ID: "${{ secrets.PROJECT_ID }}"
  GCR_REGION: "${{ secrets.GCR_REGION }}"
  GCR_SERVICE: "${{ secrets.GCR_SERVICE }}"
  GAR_REGION: "${{ secrets.GAR_REGION }}"
  GAR_REPO_NAME: "${{ secrets.GAR_REPO_NAME }}"
  GAR_IMAGE_NAME: "${{ secrets.GAR_IMAGE_NAME }}"

jobs:
  deploy:
    runs-on: "ubuntu-latest"

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Authenticate to GCP"
        id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDS }}"

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Docker Auth To GAR"
        run: |
          gcloud auth configure-docker "${{env.GAR_REGION}}-docker.pkg.dev"

      - name: "Build and Push To GAR"
        run: |-
          DOCKER_TAG="${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/${{ env.GAR_IMAGE_NAME }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.GCR_SERVICE }}
          image: ${{ env.GAR_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPO_NAME }}/${{ env.GAR_IMAGE_NAME }}:${{ github.sha }}
          region: ${{ env.GCR_REGION }}
          port: 8457
          allow_unauthenticated: true
          env_vars: |-
            AUTH_SERVER_PORT=${{ secrets.AUTH_SERVER_PORT }}
            FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}
            FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}
            FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
            FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}
            FIREBASE_DATABASE_URL=${{ secrets.FIREBASE_DATABASE_URL }}
            FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
            FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}
            FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}
            FIREBASE_SERVICE_CRED_KEY=${{ secrets.FIREBASE_SERVICE_CRED_KEY }}

      - name: "Show output"
        run: |2-
          echo ${{ steps.deploy.outputs.url }}
